### ISSUE TITLE
1.week, 1.month result not correct?

### ISSUE THREAD

**Issue by seaify** [brianhempel/rounding#1]
```
2.3.5 :018 > Time.now.floor_to(1.week)
2017-10-26 00:00:00 +0800
2.3.5 :019 > Time.now.floor_to(1.month)
2017-10-01 07:54:18 +0800
```
@brianhempel

**Comment by brianhempel** [comment]
No bug.

(1) The UNIX epoch is a Thursday, so it rounds to the nearest Thursday: you are expected to provide an offset around which to round for weeks. From the README:

```ruby
# round to Wednesday

wednesday = Time.parse("2014-09-03 -0400")
one_week  = ONE_DAY*7

time.round_to(one_week, wednesday) # => 2014-09-10 00:00:00 -0400
```

(2)  Rounding only does rounding of regular intervals. From the README: "For rounding to the month or year, you should use [ActiveSupport's time extensions](http://edgeguides.rubyonrails.org/active_support_core_extensions.html#extensions-to-date). Months and years have variable numbers of days and thus are not correctly supported by Rounding." It looks like `1.month` is now 30.4 days.

```
$ ruby -r active_support/time -e "p 1.month.to_f / 1.day"
30.436875
```
